<a href="https://colab.research.google.com/github/svgoudar/My-Data-Science-Roadmap/blob/main/Pandas_and_Numpy/Panda/5.Selection_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df_loan_applications = pd.read_csv("https://raw.githubusercontent.com/svgoudar/datasets/refs/heads/main/loan_applications.csv")
df_transactions = pd.read_csv("https://raw.githubusercontent.com/svgoudar/datasets/refs/heads/main/transactions.csv")

In [5]:
df_loan_applications = df_loan_applications.set_index('customer_id')

In [13]:
df_loan_applications.reset_index(inplace=True)

In [34]:
df_loan_applications[df_loan_applications['customer_id'] < 'CUST109427']['customer_id'].max()

'CUST109426'

In [15]:
df_loan_applications['applicant_age']

0        28
1        44
2        56
3        27
4        50
         ..
49995    55
49996    61
49997    48
49998    62
49999    46
Name: applicant_age, Length: 50000, dtype: int64

In [17]:
df_loan_applications[['applicant_age','loan_type']]

       applicant_age       loan_type
0                 28   Business Loan
1                 44        Car Loan
2                 56  Education Loan
3                 27        Car Loan
4                 50   Personal Loan
...              ...             ...
49995             55  Education Loan
49996             61  Education Loan
49997             48        Car Loan
49998             62   Business Loan
49999             46       Home Loan

[50000 rows x 2 columns]

In [22]:
print(df_loan_applications.iloc[0])
print("\n")
print(df_loan_applications.loc[0])

customer_id                                                         CUST109427
application_id                            c8bf0bea-70e6-4870-9125-41b8210c527f
application_date                                                    2023-04-09
loan_type                                                        Business Loan
loan_amount_requested                                                 604000.0
loan_tenure_months                                                          12
interest_rate_offered                                                    11.66
purpose_of_loan                                              Medical Emergency
employment_status                                                      Retired
monthly_income                                                         34700.0
cibil_score                                                                714
existing_emis_monthly                                                   1100.0
debt_to_income_ratio                                                      3.17
property_ownership_status                                               Rented
residential_address          94/31, Sehgal Zila, Vadodara-380521, Anantapur...
applicant_age                                                               28
gender                                                                  Female
number_of_dependents                                                         3
loan_status                                                           Approved
fraud_flag                                                                   0
fraud_type                                                                 NaN
Name: 0, dtype: object


customer_id                                                         CUST109427
application_id                            c8bf0bea-70e6-4870-9125-41b8210c527f
application_date                                                    2023-04-09
loan_type                                                        Business Loan
loan_amount_requested                                                 604000.0
loan_tenure_months                                                          12
interest_rate_offered                                                    11.66
purpose_of_loan                                              Medical Emergency
employment_status                                                      Retired
monthly_income                                                         34700.0
cibil_score                                                                714
existing_emis_monthly                                                   1100.0
debt_to_income_ratio                                                      3.17
property_ownership_status                                               Rented
residential_address          94/31, Sehgal Zila, Vadodara-380521, Anantapur...
applicant_age                                                               28
gender                                                                  Female
number_of_dependents                                                         3
loan_status                                                           Approved
fraud_flag                                                                   0
fraud_type                                                                 NaN
Name: 0, dtype: object

In [23]:
df = df_loan_applications.set_index('customer_id')

| Feature          | `.loc`                        | `.iloc`                      |
| ---------------- | ----------------------------- | ---------------------------- |
| Indexes by       | **Label names**               | **Integer positions**        |
| Works with       | Index names & col names       | Row/col numbers (0,1,2)      |
| Slices are       | **Inclusive** of end          | **Exclusive** of end         |
| Typical use case | When index/columns have names | When treating as pure matrix |

In [29]:
df_loan_applications.loc[:10,['customer_id','application_id']]

   customer_id                        application_id
0   CUST109427  c8bf0bea-70e6-4870-9125-41b8210c527f
1   CUST106146  91224cec-3544-4bc7-ac15-a9792da54c02
2   CUST100674  4efcd02d-4a03-4ab7-9bd1-0ff430493d0c
3   CUST106466  a61337d4-ba04-4a68-b492-2cb8266e6ed7
4   CUST112319  a8d1639e-170b-41b2-826a-55c7dae38d16
5   CUST116153  d91cf990-efa1-44ad-94bf-44e6c79d1051
6   CUST118841  cd837d7e-98de-4d26-8b6f-f59d7bef9d2a
7   CUST109691  63e87083-c21d-4b53-856b-b58b3285b9aa
8   CUST106322  7eb31cc3-e1e7-4ef9-ae4e-b86771d60119
9   CUST102418  74126982-ef72-40dd-8cc3-5d441cfe7b02
10  CUST101535  2cdc104f-abbf-4f8d-b9c1-2e073ed17bb7

In [35]:
  df_loan_applications.loc[df_loan_applications['customer_id'] < 'CUST101535']

,customer_id,application_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,...,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
2,CUST100674,4efcd02d-4a03-4ab7-9bd1-0ff430493d0c,2023-05-22,Education Loan,431000.0,60,11.40,Medical Emergency,Self-Employed,14800.0,...,4600.0,31.08,Rented,"H.No. 81, Dutta Path, Kozhikode-340301, Tadepa...",56,Other,4,Approved,0,NaN
11,CUST101333,0e6ce97f-296f-41e7-88a5-0a4951e4262d,2023-11-09,Home Loan,256000.0,120,8.86,Medical Emergency,Unemployed,87300.0,...,1600.0,1.83,Rented,"72, Sandal Nagar, Machilipatnam 027510, Raurke...",63,Male,1,Approved,0,NaN
18,CUST101064,10bb2424-c9be-4ede-b054-5943e4bed62b,2024-08-26,Education Loan,526000.0,120,12.18,Home Renovation,Salaried,40900.0,...,2100.0,5.13,Owned,"67, Mallick Marg, Ichalkaranji 420767, Jodhpur...",48,Male,0,Declined,0,NaN
39,CUST100101,d1b05115-e018-4741-8aa8-e5068bcd2484,2023-07-30,Car Loan,306000.0,240,10.29,Wedding,Business Owner,39500.0,...,2600.0,6.58,Jointly Owned,"H.No. 78, Raju Path, Phagwara-915579, Bihar Sh...",30,Female,4,Declined,0,NaN
52,CUST100826,27ab215f-4f9c-492b-9c19-dedef1f690a0,2024-03-23,Personal Loan,100000.0,12,10.56,Home Renovation,Student,89500.0,...,3700.0,4.13,Rented,"H.No. 340, Golla Zila, North Dumdum 466075, Ra...",50,Other,4,Declined,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49918,CUST100184,58bf9bbb-70b9-4668-9260-14c168ede7d0,2025-01-01,Business Loan,712000.0,24,12.65,Wedding,Self-Employed,44400.0,...,7400.0,16.67,Jointly Owned,"49, Sunder Ganj, Motihari 368663, Pali, Uttara...",22,Male,0,Approved,0,NaN
49944,CUST101388,f649f9ed-631d-4b9d-98b4-e875b96d74a5,2023-02-20,Car Loan,605000.0,360,15.91,Business Expansion,Retired,50800.0,...,2200.0,4.33,Rented,"H.No. 49, Sawhney Path, Sirsa-273174, Bahraich...",44,Other,0,Approved,0,NaN
49951,CUST100444,fe05ce1e-4f64-4227-8497-802b9f8b6eb9,2025-01-12,Personal Loan,517000.0,120,9.05,Debt Consolidation,Student,17400.0,...,6000.0,34.48,Jointly Owned,"53, Bhardwaj Marg, Madhyamgram 156277, Noida, ...",50,Other,0,Approved,0,NaN
49957,CUST101018,a9c0c7ca-7796-4a72-a524-f0cbc17e82d9,2024-02-10,Personal Loan,698000.0,240,7.37,Debt Consolidation,Business Owner,42000.0,...,3900.0,9.29,Jointly Owned,"H.No. 687, Golla Ganj, Nizamabad-345146, Jamal...",32,Male,4,Approved,0,NaN
49962,CUST101224,e1bcb9de-02c1-4454-b4e3-39d0d68a6e71,2024-11-15,Business Loan,843000.0,12,9.40,Education,Salaried,45400.0,...,5300.0,11.67,Jointly Owned,"69/473, Kunda Nagar, Dewas-353212, Baranagar, ...",62,Female,4,Declined,0,NaN

In [39]:
df_loan_applications.loc[df_loan_applications['monthly_income'] < 50000,['customer_id','application_id','monthly_income']]

      customer_id                        application_id  monthly_income
0      CUST109427  c8bf0bea-70e6-4870-9125-41b8210c527f         34700.0
2      CUST100674  4efcd02d-4a03-4ab7-9bd1-0ff430493d0c         14800.0
3      CUST106466  a61337d4-ba04-4a68-b492-2cb8266e6ed7         28800.0
4      CUST112319  a8d1639e-170b-41b2-826a-55c7dae38d16         43900.0
6      CUST118841  cd837d7e-98de-4d26-8b6f-f59d7bef9d2a         47300.0
...           ...                                   ...             ...
49989  CUST118628  5c2ff689-ef1a-417e-8cff-a07d716f12df         31700.0
49995  CUST114840  1d4b1017-e8a1-4a7b-94d1-63e90b05d665         49200.0
49996  CUST103055  2984426c-6d0b-437c-9a13-84bf3244c6d4         28600.0
49997  CUST119886  cdbc7ad8-0f23-46c4-aaca-619053ad5605         42000.0
49998  CUST109088  46a8f901-8005-4ae7-923e-f9d0dc8e0ae8         46700.0

[24717 rows x 3 columns]

In [40]:
df_loan_applications.loc[df_loan_applications['monthly_income'] < 50000,['customer_id','application_id','monthly_income']]

      customer_id                        application_id  monthly_income
0      CUST109427  c8bf0bea-70e6-4870-9125-41b8210c527f         34700.0
2      CUST100674  4efcd02d-4a03-4ab7-9bd1-0ff430493d0c         14800.0
3      CUST106466  a61337d4-ba04-4a68-b492-2cb8266e6ed7         28800.0
4      CUST112319  a8d1639e-170b-41b2-826a-55c7dae38d16         43900.0
6      CUST118841  cd837d7e-98de-4d26-8b6f-f59d7bef9d2a         47300.0
...           ...                                   ...             ...
49989  CUST118628  5c2ff689-ef1a-417e-8cff-a07d716f12df         31700.0
49995  CUST114840  1d4b1017-e8a1-4a7b-94d1-63e90b05d665         49200.0
49996  CUST103055  2984426c-6d0b-437c-9a13-84bf3244c6d4         28600.0
49997  CUST119886  cdbc7ad8-0f23-46c4-aaca-619053ad5605         42000.0
49998  CUST109088  46a8f901-8005-4ae7-923e-f9d0dc8e0ae8         46700.0

[24717 rows x 3 columns]

In [42]:
df_loan_applications[df_loan_applications['cibil_score'] > 720]

,customer_id,application_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,...,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
2,CUST100674,4efcd02d-4a03-4ab7-9bd1-0ff430493d0c,2023-05-22,Education Loan,431000.0,60,11.40,Medical Emergency,Self-Employed,14800.0,...,4600.0,31.08,Rented,"H.No. 81, Dutta Path, Kozhikode-340301, Tadepa...",56,Other,4,Approved,0,NaN
6,CUST118841,cd837d7e-98de-4d26-8b6f-f59d7bef9d2a,2023-02-02,Personal Loan,220000.0,36,8.71,Vehicle Purchase,Unemployed,47300.0,...,6700.0,14.16,Rented,"805, Bhakta Path, Thiruvananthapuram-330918, K...",46,Male,1,Approved,0,NaN
8,CUST106322,7eb31cc3-e1e7-4ef9-ae4e-b86771d60119,2025-05-11,Personal Loan,106000.0,120,10.22,Business Expansion,Business Owner,40300.0,...,4500.0,11.17,Owned,"65, Dani Path, Tirunelveli 460530, Jalna, Utta...",42,Female,4,Approved,0,NaN
11,CUST101333,0e6ce97f-296f-41e7-88a5-0a4951e4262d,2023-11-09,Home Loan,256000.0,120,8.86,Medical Emergency,Unemployed,87300.0,...,1600.0,1.83,Rented,"72, Sandal Nagar, Machilipatnam 027510, Raurke...",63,Male,1,Approved,0,NaN
14,CUST103082,973a866a-a7bd-4166-8121-a1e220e29a83,2023-12-16,Education Loan,737000.0,240,7.00,Medical Emergency,Retired,10000.0,...,5500.0,55.00,Jointly Owned,"H.No. 88, Dube Nagar, Nanded 255803, Khammam, ...",28,Male,2,Approved,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,CUST115955,c7e837fb-11b8-44d3-a093-45c899cfe38c,2023-11-22,Car Loan,606000.0,120,9.73,Medical Emergency,Student,65700.0,...,3400.0,5.18,Rented,"H.No. 35, Rajan Street, Ichalkaranji 261561, A...",30,Female,0,Approved,0,NaN
49995,CUST114840,1d4b1017-e8a1-4a7b-94d1-63e90b05d665,2024-12-29,Education Loan,381000.0,24,12.05,Vehicle Purchase,Student,49200.0,...,2400.0,4.88,Rented,"28, Rana Path, Gorakhpur-411614, Tirupati, Mah...",55,Other,3,Approved,0,NaN
49996,CUST103055,2984426c-6d0b-437c-9a13-84bf3244c6d4,2022-06-17,Education Loan,736000.0,120,11.03,Medical Emergency,Student,28600.0,...,4000.0,13.99,Jointly Owned,"20/836, Varma Zila, Udaipur-879473, Rajkot, We...",61,Other,0,Approved,0,NaN
49997,CUST119886,cdbc7ad8-0f23-46c4-aaca-619053ad5605,2024-12-14,Car Loan,436000.0,12,10.98,Wedding,Student,42000.0,...,600.0,1.43,Jointly Owned,"H.No. 505, Luthra Zila, Panchkula 991795, Kolh...",48,Other,4,Approved,0,NaN
49998,CUST109088,46a8f901-8005-4ae7-923e-f9d0dc8e0ae8,2022-12-16,Business Loan,827000.0,24,16.18,Vehicle Purchase,Business Owner,46700.0,...,8100.0,17.34,Rented,"H.No. 697, Sathe Road, Ongole 444116, Satna, A...",62,Other,3,Approved,0,NaN

In [48]:
print(df_loan_applications.iloc[:20,[0,4,5]].sample(2))
print("\n")
print(df_loan_applications.iloc[:20,0:5].sample(2))

   customer_id  loan_amount_requested  loan_tenure_months
1   CUST106146               100000.0                 240
10  CUST101535               395000.0                  12


  customer_id                        application_id application_date  \
1  CUST106146  91224cec-3544-4bc7-ac15-a9792da54c02       2023-09-23
7  CUST109691  63e87083-c21d-4b53-856b-b58b3285b9aa       2022-11-05

   loan_type  loan_amount_requested
1   Car Loan               100000.0
7  Home Loan               475000.0

In [58]:
df_loan_applications.query('loan_amount_requested > 500000').sample(2)

df_loan_applications.query('loan_amount_requested > 500000 and applicant_age < 40').sample(2)
# print("==================")
df_loan_applications.query('loan_type in ["Car Loan", "Education Loan"]').sample(2)
# print("==================")

,customer_id,application_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,...,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
46957,CUST109948,48b4a653-b489-495d-b97f-46906de6ff81,2025-05-27,Education Loan,174000.0,60,8.00,Education,Business Owner,45000.0,...,4700.0,10.44,Owned,"71/032, Dhawan Road, Hosur 644887, Kurnool, Ma...",24,Female,0,Approved,0,NaN
12669,CUST117455,98e91e4a-3652-4e9f-b436-791143a373f5,2022-06-27,Education Loan,266000.0,24,12.44,Medical Emergency,Self-Employed,72500.0,...,4200.0,5.79,Rented,"H.No. 171, Borah Circle, Kavali 295724, Machil...",42,Female,0,Approved,0,NaN

In [59]:
df= df_loan_applications.copy()
df_trans = df_transactions.copy()

In [65]:
# Select columns by exact names
df.filter(items=['customer_id', 'loan_amount_requested'], axis=1)

# Select columns by regex
df.filter(regex='^loan', axis=1)   # picks all columns starting with 'loan'

# df.set_index('customer_id',inplace=True)
# Select rows by index label list

df.filter(items=[0, 1], axis=0)  # only if customer_id is the index

,customer_id,application_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,...,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
0,CUST109427,c8bf0bea-70e6-4870-9125-41b8210c527f,2023-04-09,Business Loan,604000.0,12,11.66,Medical Emergency,Retired,34700.0,...,1100.0,3.17,Rented,"94/31, Sehgal Zila, Vadodara-380521, Anantapur...",28,Female,3,Approved,0,NaN
1,CUST106146,91224cec-3544-4bc7-ac15-a9792da54c02,2023-09-23,Car Loan,100000.0,240,13.62,Education,Unemployed,51600.0,...,0.0,0.00,Owned,"H.No. 00, Sheth Chowk, Ichalkaranji 006728, Im...",44,Other,3,Approved,0,NaN

In [66]:
df[df['loan_type'].isin(['Car Loan', 'Education Loan'])]

,customer_id,application_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,...,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
1,CUST106146,91224cec-3544-4bc7-ac15-a9792da54c02,2023-09-23,Car Loan,100000.0,240,13.62,Education,Unemployed,51600.0,...,0.0,0.00,Owned,"H.No. 00, Sheth Chowk, Ichalkaranji 006728, Im...",44,Other,3,Approved,0,NaN
2,CUST100674,4efcd02d-4a03-4ab7-9bd1-0ff430493d0c,2023-05-22,Education Loan,431000.0,60,11.40,Medical Emergency,Self-Employed,14800.0,...,4600.0,31.08,Rented,"H.No. 81, Dutta Path, Kozhikode-340301, Tadepa...",56,Other,4,Approved,0,NaN
3,CUST106466,a61337d4-ba04-4a68-b492-2cb8266e6ed7,2024-07-09,Car Loan,324000.0,120,10.36,Debt Consolidation,Self-Employed,28800.0,...,4000.0,13.89,Rented,"H.No. 022, Rege Road, Tiruvottiyur-927857, Aur...",27,Other,4,Declined,0,NaN
10,CUST101535,2cdc104f-abbf-4f8d-b9c1-2e073ed17bb7,2024-10-19,Education Loan,395000.0,12,8.33,Debt Consolidation,Salaried,10100.0,...,0.0,0.00,Jointly Owned,"46/02, Buch Zila, Chinsurah-642812, Buxar, Miz...",40,Male,4,Approved,0,NaN
12,CUST106264,e0b509dc-5357-427d-bd69-681308a68efc,2024-08-31,Education Loan,745000.0,12,9.78,Debt Consolidation,Self-Employed,35000.0,...,0.0,0.00,Rented,"H.No. 75, Contractor Ganj, Bhiwandi-559674, Si...",61,Female,1,Declined,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49993,CUST117199,0265b56d-44bc-4342-a50b-0e298dd73063,2024-10-20,Car Loan,587000.0,24,9.03,Medical Emergency,Business Owner,50700.0,...,400.0,0.79,Owned,"H.No. 59, Mangal Road, Nagercoil-198543, Kanpu...",33,Other,3,Approved,0,NaN
49994,CUST115955,c7e837fb-11b8-44d3-a093-45c899cfe38c,2023-11-22,Car Loan,606000.0,120,9.73,Medical Emergency,Student,65700.0,...,3400.0,5.18,Rented,"H.No. 35, Rajan Street, Ichalkaranji 261561, A...",30,Female,0,Approved,0,NaN
49995,CUST114840,1d4b1017-e8a1-4a7b-94d1-63e90b05d665,2024-12-29,Education Loan,381000.0,24,12.05,Vehicle Purchase,Student,49200.0,...,2400.0,4.88,Rented,"28, Rana Path, Gorakhpur-411614, Tirupati, Mah...",55,Other,3,Approved,0,NaN
49996,CUST103055,2984426c-6d0b-437c-9a13-84bf3244c6d4,2022-06-17,Education Loan,736000.0,120,11.03,Medical Emergency,Student,28600.0,...,4000.0,13.99,Jointly Owned,"20/836, Varma Zila, Udaipur-879473, Rajkot, We...",61,Other,0,Approved,0,NaN
49997,CUST119886,cdbc7ad8-0f23-46c4-aaca-619053ad5605,2024-12-14,Car Loan,436000.0,12,10.98,Wedding,Student,42000.0,...,600.0,1.43,Jointly Owned,"H.No. 505, Luthra Zila, Panchkula 991795, Kolh...",48,Other,4,Approved,0,NaN

In [67]:
df.isin(['Car Loan', 'Education Loan'])

,customer_id,application_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,...,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49996,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49997,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [71]:
df = df.set_index('customer_id')

In [76]:
df.at['CUST109427', 'loan_amount_requested']

customer_id
CUST109427    604000.0
CUST109427    913000.0
CUST109427    664000.0
CUST109427    453000.0
CUST109427    408000.0
CUST109427    538000.0
CUST109427    100000.0
CUST109427    624000.0
Name: loan_amount_requested, dtype: float64

| Function   | Used for                       | Example                                        |
| ---------- | ------------------------------ | ---------------------------------------------- |
| `query()`  | Row filter by string expr      | `df.query('Age > 30 and Gender=="Male"')`      |
| `filter()` | Select cols/rows by name/regex | `df.filter(regex='^loan', axis=1)`             |
| `isin()`   | Check membership               | `df[df['loan_type'].isin(['Car', 'Edu'])]`     |
| `at[]`     | Single value by label          | `df.at['CUST109427', 'loan_amount_requested']` |

| Purpose                 | Example                            |
| ----------------------- | ---------------------------------- |
| Single col select       | `df['Name']`                       |
| Multi col select        | `df[['Name', 'Age']]`              |
| Row by label            | `df.loc[2]`                        |
| Row by position         | `df.iloc[2]`                       |
| Row+col slice by label  | `df.loc[2, 'Name']`                |
| Row+col slice by pos    | `df.iloc[2, 0]`                    |
| Boolean condition       | `df[df['Age'] > 30]`               |
| Query string            | `df.query('Age > 30')`             |
| Filter columns by regex | `df.filter(regex='^A', axis=1)`    |
| Membership check        | `df[df['Name'].isin(['A','B'])]`   |
| Fast scalar access      | `df.at[2, 'Name']` / `df.iat[2,0]` |